Separate user sessions app
raeeschachar/phone_directory pull request #12
Opened 2017-12-31 11:15 UTC by raeeschachar

2017-12-31 11:15 UTC, raeeschachar commented
@marykhan

2017-12-31 11:44 UTC, MaryKhan requested changes

2017-12-31 11:44 UTC, MaryKhan commented on user_sessions/apps.py
> +class LoginConfig(AppConfig):
rename it to UserSessionsConfig.

2017-12-31 11:44 UTC, MaryKhan commented on user_sessions/urls.py
> +    url(r'^user_sessions/?$', views.LoginView.as_view(), name='login'),
url should be `login` here.

2017-12-31 11:44 UTC, MaryKhan commented on user_sessions/views.py
> +    template_name = 'phone_directory/home.html'
this template is associated with HomePageView. we should not render it directly from here, instead redirect to home view after logout.

2018-01-02 06:22 UTC, MaryKhan approved these changes
good to merge!

2018-01-02 14:21 UTC, merged