Added add contact form
raeeschachar/phone_directory pull request #4
Opened 2017-12-10 23:03 UTC by raeeschachar

2017-12-10 23:04 UTC, raeeschachar commented
@MaryKhan

2017-12-11 06:40 UTC, MaryKhan requested changes

2017-12-11 06:40 UTC, MaryKhan commented on contacts/forms.py
> +class AddContactForm(forms.ModelForm):
seems like we're not using this form anywhere.

2017-12-11 12:21 UTC, MaryKhan requested changes

2017-12-11 12:21 UTC, MaryKhan commented on contacts/templates/contacts/contact_list.html
> +    <a href="/contacts/add_contact">Add Contact</a>
use `{% url '<url-name>' %}` instead.

2017-12-11 12:21 UTC, MaryKhan commented on contacts/views.py
> +    success_url = "/contacts"
same here!
don't use hard-coded url anywhere in project.

2017-12-11 18:27 UTC, merged