added delete functionality
raeeschachar/phone_directory pull request #9
Opened 2017-12-18 19:45 UTC by raeeschachar

2017-12-18 19:58 UTC, raeeschachar commented
@marykhan

2017-12-19 17:33 UTC, MaryKhan requested changes

2017-12-19 17:33 UTC, MaryKhan commented on contacts/models.py
> +from django.core.validators import RegexValidator, EmailValidator
remove this import `EmailValidator`. :P

2017-12-19 17:33 UTC, MaryKhan commented on contacts/urls.py
> +    url(r'^delete/(?P<pk>\d+)$', views.DeleteContactView.as_view(), name='delete_contact')
optional slash please?

2017-12-19 19:52 UTC, raeeschachar commented
@MaryKhan Done.

2017-12-20 13:37 UTC, merged